language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '10'
services:
  - xvfb
cache: 
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash 
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
after_success:
  - yarn coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
