language: node_js
sudo: required
notifications:
  email: false
node_js:
  - '10'
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - npm install coveralls --save-dev
after_success:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
